# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uy-VEVKB4YDWg1nlsxDTJshYZ4VC7HGJ
"""

import re
import json

# 预定义的可能疾病
possible_diseases = [
    "acute coronary syndrome",
    "myocardial infarction",
    "unstable angina",
    "pneumonia",
    "pulmonary embolism",
    "chronic obstructive pulmonary disease",
    "asthma",
    "heart failure",
    "gastroesophageal reflux disease",
    "diabetes mellitus",
    "hypertension",
    "stroke",
    "sepsis",
    "renal failure",
    "appendicitis",
    "gallbladder disease",
    "deep vein thrombosis"
]

# 预定义的就诊科室
departments = [
    "emergency department",
    "cardiology department",
    "internal medicine",
    "pulmonology",
    "neurology",
    "gastroenterology",
    "orthopedics",
    "urology",
    "infectious disease",
    "general surgery",
    "endocrinology",
    "rheumatology",
    "psychiatry",
    "pediatrics"
]

# 预定义的治疗选项
treatment_options_list = [
    "electrocardiograms",
    "blood tests",
    "echocardiography",
    "coronary angiography",
    "medications",
    "lifestyle modifications",
    "cardiac rehabilitation",
    "surgery",
    "oxygen therapy",
    "intravenous fluids",
    "antibiotics",
    "bronchodilators",
    "inhalers",
    "insulin therapy",
    "pain management"
]

# 默认值
default_possible_disease = "unknown disease"
default_department = "general practice"
default_treatment_options = "standard care"

def extract_info(input_text):
    # 提取 Q 和 A 部分
    question_match = re.search(r'Q：(.+?)A：', input_text, re.DOTALL)
    answer_match = re.search(r'A：(.+)', input_text, re.DOTALL)

    if not question_match or not answer_match:
        return json.dumps({"error": "Invalid input format"}, indent=4)

    question = question_match.group(1).strip()
    answer = answer_match.group(1).strip()

    # 提取基本信息
    age = re.search(r'(\d+)-year-old', question)
    gender = re.search(r'(male|female)', question)

    # 提取症状
    symptoms_match = re.search(r'with\s+(.+?)(?:\.|$)', question)
    symptoms = symptoms_match.group(1).split(' and ') if symptoms_match else []

    # 提取可能的疾病
    possible_disease = default_possible_disease
    for disease in possible_diseases:
        if disease in answer.lower():
            possible_disease = disease
            break

    # 提取就诊科室
    department = default_department
    for dept in departments:
        if dept in answer.lower():
            department = dept
            break

    # 提取治疗选项
    treatment_options = []
    for option in treatment_options_list:
        if option in answer.lower():
            treatment_options.append(option)

    # 如果没有提取到治疗选项，使用默认值
    treatment_options_str = ', '.join(treatment_options) if treatment_options else default_treatment_options

    # 构造 JSON 数据
    report = {
        "basic info": {
            "age": int(age.group(1)) if age else None,
            "gender": gender.group(1) if gender else None,
            "medicalHistory": "string",
            "familyHistory": "string"
        },
        "prompts": {
            "symptoms": [symptom.strip() for symptom in symptoms]
        },
        "diagnosis": {
            "possibleDisease": possible_disease,
            "department": department,
            "treatmentOptions": treatment_options_str
        }
    }

    return json.dumps(report, indent=4)

# 示例使用
input_text = """Q：A 45-year-old male with chest pain and shortness of breath. What is the most likely diagnosis, and which department should he go to for a consultation?A：Based on the symptoms provided, the most likely diagnosis would be acute coronary syndrome (ACS). The patient may have unstable angina or myocardial infarction (heart attack). The patient should be taken to the emergency department for an immediate consultation. In the emergency department, he will receive a thorough evaluation and treatment by cardiologists and other healthcare professionals. They will perform tests such as electrocardiograms (ECGs), blood tests, and possibly cardiac imaging studies like echocardiography or coronary angiography to confirm the diagnosis and determine the extent of damage to the heart. Once the patient is stabilized and treated for any acute issues, he may be referred to a cardiology department for further management and follow-up care. This could include medications, lifestyle modifications, cardiac rehabilitation, or possibly interventions like stenting or bypass surgery."""

report_json = extract_info(input_text)
print(report_json)